version: '3.8'

services:
  backend:
    container_name: lightcone-server
    build:
      context: ./lightcone_clj
      dockerfile: Dockerfile.dev
    volumes:
      - ./lightcone_clj:/app
      - /app/target
    ports:
      - "3003:3000"  # Main backend API port
      - "9000:9000"  # nREPL port
      - "5556:5555"  # Portal UI port
    environment:
      - ENVIRONMENT=development
      - PORT=3000
      - ARCHIVIST_SERVICE_URL=http://archivist:3000
      - CLARITY_SERVICE_URL=http://clarity-clj:3002
    networks:
      - lightcone-net
      - rlc-net
    command: clj -M:server

  frontend:
    container_name: lightcone-web-ui
    build:
      context: ./lightcone_ts
      dockerfile: Dockerfile.dev
    volumes:
      - ./lightcone_ts:/src  # This matches the WORKDIR in Dockerfile
      - /src/node_modules  # Update this to match WORKDIR
    ports:
      - "3004:5173"
    environment:
      - VITE_PUBLIC_ARCHIVIST_URL=http://64.23.130.139:3000
      - VITE_PUBLIC_LIGHTCONE_SERVER_URL=http://64.23.130.139:3003
      # - VITE_PUBLIC_ARCHIVIST_URL=http://localhost:3000
      # - VITE_PUBLIC_LIGHTCONE_SERVER_URL=http://localhost:3003
    networks:
      - lightcone-net
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

networks:
  lightcone-net:
    name: lightcone-net
  rlc-net:
    external: true    # This tells Docker this network already exists
