version: '3.8'

services:
  backend:
    container_name: lightcone-server
    build:
      context: ./lightcone_clj
      dockerfile: Dockerfile.dev
    volumes:
      - ./lightcone_clj:/app
      - /app/target
    ports:
      - "3003:3000"  # Main backend API port
      - "9000:9000"  # nREPL port
      - "5556:5555"  # Portal UI port
    environment:
      - ENVIRONMENT=development
      - PORT=3000
      - ARCHIVIST_SERVICE_URL=http://archivist:3000
      - CLARITY_SERVICE_URL=http://clarity-clj:3002
    networks:
      - lightcone-net
      - rlc-net
    command: clj -M:server

  frontend:
    container_name: lightcone-web-ui
    build:
      context: ./lightcone_ts
      dockerfile: Dockerfile.dev
    volumes:
      - ./lightcone_ts:/app
      - /app/node_modules
    ports:
      - "3004:3000"
    environment:
      - NEXT_PUBLIC_ARCHIVIST_URL=http://backend:3000
      - NEXT_PUBLIC_LIGHTCONE_SERVER_URL=http://localhost:3003
    networks:
      - lightcone-net
    depends_on:
      - backend
    command: npm run dev

networks:
  lightcone-net:
    name: lightcone-net
  rlc-net:
    external: true    # This tells Docker this network already exists
