FROM node:20

WORKDIR /src

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Default command (can be overridden in docker-compose)
CMD ["npm", "run", "dev"]
